# Generated by Django 4.2.27 on 2026-01-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('pgn', models.TextField(blank=True, default='')),
                ('is_game_over', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('white_player_type', models.CharField(default='human', max_length=20)),
                ('black_player_type', models.CharField(default='human', max_length=20)),
            ],
        ),
    ]
