# Generated by Django 4.2.27 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_player_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
