# Generated by Django 4.2.27 on 2026-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_black_player_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='white_player_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
