"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i3fuzw5)ra*qpb5m_&)6!!_*yxd^#&yp3uu#^&+e@nm_1x=bc0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def _parse_bool(value, default=False):
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _parse_csv(value, default):
    if not value:
        return default
    return [item.strip() for item in value.split(',') if item.strip()]


LLM_FEATURE_ENABLED = _parse_bool(os.getenv('LLM_FEATURE_ENABLED'), True)

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
LOCAL_LLM_ENABLED = _parse_bool(os.getenv('LOCAL_LLM_ENABLED'), True)
LOCAL_LLM_BASE_URL = os.getenv('LOCAL_LLM_BASE_URL', 'http://127.0.0.1:11434').rstrip('/')

LLM_ALLOWED_MODELS_OPENAI = _parse_csv(
    os.getenv('LLM_ALLOWED_MODELS_OPENAI'),
    ['gpt-4.1-mini', 'gpt-4o-mini'],
)
LLM_ALLOWED_MODELS_ANTHROPIC = _parse_csv(
    os.getenv('LLM_ALLOWED_MODELS_ANTHROPIC'),
    ['claude-3-5-sonnet-latest', 'claude-3-5-haiku-latest'],
)
LLM_ALLOWED_MODELS_GEMINI = _parse_csv(
    os.getenv('LLM_ALLOWED_MODELS_GEMINI'),
    ['gemini-1.5-pro', 'gemini-1.5-flash'],
)
LLM_ALLOWED_MODELS_LOCAL = _parse_csv(
    os.getenv('LLM_ALLOWED_MODELS_LOCAL'),
    ['llama3.1:8b'],
)

LLM_ADVANCED_CUSTOM_MODEL_ENABLED = _parse_bool(
    os.getenv('LLM_ADVANCED_CUSTOM_MODEL_ENABLED'),
    True,
)
LLM_MOVE_TIMEOUT_SECONDS = float(os.getenv('LLM_MOVE_TIMEOUT_SECONDS', '15'))

ANALYSIS_FEATURE_ENABLED = _parse_bool(os.getenv('ANALYSIS_FEATURE_ENABLED'), True)
ANALYSIS_PROFILE_DEFAULT = os.getenv('ANALYSIS_PROFILE_DEFAULT', 'balanced')
ANALYSIS_MIN_PLIES = int(os.getenv('ANALYSIS_MIN_PLIES', '8'))
ANALYSIS_MAX_PLIES = int(os.getenv('ANALYSIS_MAX_PLIES', '160'))
ANALYSIS_TIME_LIMIT_SECONDS_BALANCED = float(
    os.getenv('ANALYSIS_TIME_LIMIT_SECONDS_BALANCED', '0.10')
)
ANALYSIS_KEY_MOVES_LIMIT = int(os.getenv('ANALYSIS_KEY_MOVES_LIMIT', '5'))
ANALYSIS_TURNING_POINTS_LIMIT = int(os.getenv('ANALYSIS_TURNING_POINTS_LIMIT', '3'))
